#!/bin/bash

# Read environment variables
MYSQL_USERNAME="${MYSQL_USERNAME:-app_user}"
MYSQL_PASSWORD="${MYSQL_PASSWORD:-Pass1234@}"
MYSQL_DATABASE="${MYSQL_DATABASE:-template_db}"

# Create the user with environment variables
mysql -u root -p${MYSQL_ROOT_PASSWORD} <<-EOSQL
CREATE USER IF NOT EXISTS '${MYSQL_USERNAME}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';
CREATE DATABASE IF NOT EXISTS ${MYSQL_DATABASE};
GRANT ALL PRIVILEGES ON ${MYSQL_DATABASE}.* TO '${MYSQL_USERNAME}'@'%';
FLUSH PRIVILEGES;
EOSQL
