export const HTTP_STATUS = {
  CONTINUE: { context: 'CONTINUE', status: 100 },
  SWITCHING_PROTOCOLS: { context: 'SWITCHING_PROTOCOLS', status: 101 },
  PROCESSING: { context: 'PROCESSING', status: 102 },
  EARLY_HINTS: { context: 'EARLY_HINTS', status: 103 },
  OK: { context: 'OK', status: 200 },
  CREATED: { context: 'CREATED', status: 201 },
  ACCEPTED: { context: 'ACCEPTED', status: 202 },
  NON_AUTHORITATIVE_INFORMATION: {
    context: 'NON_AUTHORITATIVE_INFORMATION',
    status: 203,
  },
  NO_CONTENT: { context: 'NO_CONTENT', status: 204 },
  RESET_CONTENT: { context: 'RESET_CONTENT', status: 205 },
  PARTIAL_CONTENT: { context: 'PARTIAL_CONTENT', status: 206 },
  MULTI_STATUS: { context: 'MULTI_STATUS', status: 207 },
  ALREADY_REPORTED: { context: 'ALREADY_REPORTED', status: 208 },
  CONTENT_DIFFERENT: { context: 'CONTENT_DIFFERENT', status: 210 },
  AMBIGUOUS: { context: 'AMBIGUOUS', status: 300 },
  MOVED_PERMANENTLY: { context: 'MOVED_PERMANENTLY', status: 301 },
  FOUND: { context: 'FOUND', status: 302 },
  SEE_OTHER: { context: 'SEE_OTHER', status: 303 },
  NOT_MODIFIED: { context: 'NOT_MODIFIED', status: 304 },
  TEMPORARY_REDIRECT: { context: 'TEMPORARY_REDIRECT', status: 307 },
  PERMANENT_REDIRECT: { context: 'PERMANENT_REDIRECT', status: 308 },
  BAD_REQUEST: { context: 'BAD_REQUEST', status: 400 },
  UNAUTHORIZED: { context: 'UNAUTHORIZED', status: 401 },
  PAYMENT_REQUIRED: { context: 'PAYMENT_REQUIRED', status: 402 },
  FORBIDDEN: { context: 'FORBIDDEN', status: 403 },
  NOT_FOUND: { context: 'NOT_FOUND', status: 404 },
  METHOD_NOT_ALLOWED: { context: 'METHOD_NOT_ALLOWED', status: 405 },
  NOT_ACCEPTABLE: { context: 'NOT_ACCEPTABLE', status: 406 },
  PROXY_AUTHENTICATION_REQUIRED: {
    context: 'PROXY_AUTHENTICATION_REQUIRED',
    status: 407,
  },
  REQUEST_TIMEOUT: { context: 'REQUEST_TIMEOUT', status: 408 },
  CONFLICT: { context: 'CONFLICT', status: 409 },
  GONE: { context: 'GONE', status: 410 },
  LENGTH_REQUIRED: { context: 'LENGTH_REQUIRED', status: 411 },
  PRECONDITION_FAILED: { context: 'PRECONDITION_FAILED', status: 412 },
  PAYLOAD_TOO_LARGE: { context: 'PAYLOAD_TOO_LARGE', status: 413 },
  URI_TOO_LONG: { context: 'URI_TOO_LONG', status: 414 },
  UNSUPPORTED_MEDIA_TYPE: { context: 'UNSUPPORTED_MEDIA_TYPE', status: 415 },
  REQUESTED_RANGE_NOT_SATISFIABLE: {
    context: 'REQUESTED_RANGE_NOT_SATISFIABLE',
    status: 416,
  },
  EXPECTATION_FAILED: { context: 'EXPECTATION_FAILED', status: 417 },
  I_AM_A_TEAPOT: { context: 'I_AM_A_TEAPOT', status: 418 },
  MISDIRECTED: { context: 'MISDIRECTED', status: 421 },
  UNPROCESSABLE_ENTITY: { context: 'UNPROCESSABLE_ENTITY', status: 422 },
  LOCKED: { context: 'LOCKED', status: 423 },
  FAILED_DEPENDENCY: { context: 'FAILED_DEPENDENCY', status: 424 },
  PRECONDITION_REQUIRED: { context: 'PRECONDITION_REQUIRED', status: 428 },
  TOO_MANY_REQUESTS: { context: 'TOO_MANY_REQUESTS', status: 429 },
  UNRECOVERABLE_ERROR: { context: 'UNRECOVERABLE_ERROR', status: 456 },
  INTERNAL_SERVER_ERROR: { context: 'INTERNAL_SERVER_ERROR', status: 500 },
  NOT_IMPLEMENTED: { context: 'NOT_IMPLEMENTED', status: 501 },
  BAD_GATEWAY: { context: 'BAD_GATEWAY', status: 502 },
  SERVICE_UNAVAILABLE: { context: 'SERVICE_UNAVAILABLE', status: 503 },
  GATEWAY_TIMEOUT: { context: 'GATEWAY_TIMEOUT', status: 504 },
  HTTP_VERSION_NOT_SUPPORTED: {
    context: 'HTTP_VERSION_NOT_SUPPORTED',
    status: 505,
  },
  INSUFFICIENT_STORAGE: { context: 'INSUFFICIENT_STORAGE', status: 507 },
  LOOP_DETECTED: { context: 'LOOP_DETECTED', status: 508 },
} as const;

export type HttpStatus = keyof typeof HTTP_STATUS;
